config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope(:path_names => { :new => "nueva", :edit => "editar" }) do
    resources :appointments, :path => 'citas'
  end
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy'
  get '/laboratorios/:id' => 'appointments#show'
  get '/laboratorios/:id/:date' => 'appointments#show'
  get '/lista' => 'appointments#list'
  get '/lista/:date' => 'appointments#list'
  root :to => 'appointments#index'
  post '/citas/marcar/:id' => 'appointments#mark'
  #root :to => 'appointments#no'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :laboratory
  belongs_to :user
  belongs_to :student

  PROGRAMMED = 1
  ASSIST     = 2
  NOT_ASSIST = 3
  DELETED    = 99
  
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  has_many :appointments
end

app/models/laboratory_admin.rb
class LaboratoryAdmin < ApplicationRecord
  belongs_to :laboratory 
  belongs_to :user 
end

app/models/staff.rb
class Staff < ApplicationRecord
  #self.table_name = "sapos_production.staffs"
end

app/models/student.rb
class Student < ApplicationRecord
  #self.table_name = "sapos_production.students"
  belongs_to :staff, :foreign_key => "supervisor", :class_name => "Staff"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :laboratory_admins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  skip_before_action :verify_authenticity_token

  def auth_required
    redirect_to '/auth/google_oauth2' unless authenticated?
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def list 
    if params[:date]
      @date = params[:date]
      @tomorrow = @date.to_date.tomorrow.strftime("%Y-%m-%d")
      @yesterday = @date.to_date.yesterday.strftime("%Y-%m-%d")
    else
  	  @date = Time.now.strftime("%Y-%m-%d")
  	  @tomorrow = Time.now.tomorrow.strftime("%Y-%m-%d")
  	  @yesterday = Time.now.yesterday.strftime("%Y-%m-%d")
  	end
    @appointments =  Appointment.where(appointment_date: @date).order(:start, :end)
    render layout: 'standalone'
  end
  
  def no
    render layout: 'standalone'
  end

  def index
  	@date = Time.now.strftime("%Y-%m-%d")
  	@tomorrow = Time.now.tomorrow.strftime("%Y-%m-%d")
  	@yesterday = Time.now.yesterday.strftime("%Y-%m-%d")
  end

  def show 
  	@laboratory = Laboratory.find(params[:id])
  	@date = params[:date]
  	@tomorrow = @date.to_date.tomorrow.strftime("%Y-%m-%d")
  	@yesterday = @date.to_date.yesterday.strftime("%Y-%m-%d")
  end

  def new
  	@laboratory = Laboratory.find(params[:laboratory_id])
  	@date = params[:date]
  	@appointment = @laboratory.appointments.new
  end

  def create
    @laboratory = Laboratory.find(params[:appointment][:laboratory_id])
    @appointment = @laboratory.appointments.new(appointment_params)
    @appointment.status = Appointment::PROGRAMMED
    @appointment.user_id = current_user.id
    if @appointment.save
      redirect_to "/laboratorios/#{@laboratory.id}/#{@appointment.appointment_date}", notice: 'Cita agregada'
    else
      redirect_to "/laboratorios/#{@laboratory.id}/#{@appointment.appointment_date}", notice: 'Error al agregar cita'
    end
  end

  def mark
    @appointment = Appointment.find(params[:id])
    @appointment.status = params[:status]
    if @appointment.save
      redirect_to "/laboratorios/#{@appointment.laboratory_id}/#{@appointment.appointment_date}", notice: 'Cita actualizada'
    else
      redirect_to "/laboratorios/#{@@appointment.laboratory_id}/#{@appointment.appointment_date}", notice: 'Error al actualizar cita'
    end
  end

  private
  def appointment_params
      params.require(:appointment).permit(:laboratory_id, :start, :end, :appointment_date, :student_id, :notes)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:user_email] = auth_hash['info']['email']

    if authenticated?
      if !session[:requested_url].blank?
        redirect_to session[:requested_url]
      else
        redirect_to '/'
      end
    else
      @title = "Error 401" 
      @message = "El usuario no está autorizado para utilizar esta aplicación."
      render layout: 'standalone', template: 'application/error', :status => 401
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end

  def failure
    @title = "Error 403" 
    @message = "El método de autenticación falló."
    render layout: 'standalone', template: 'application/error', :status => 403
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def authenticated?
    if session[:user_email].blank? 
      session[:requested_url] = request.original_url
      return false
    end
    if session[:user_auth].blank?

      user = User.where(email: session[:user_email]).first

      session[:user_auth] = user && user.email == session[:user_email]
      if session[:user_auth]
        session[:user_id] = user.id
      end
    else
      session[:user_auth]
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/list.html.erb
<h1 class="day">
<a href="/lista/<%= @yesterday %>"><span class="icon"><i class="fas fa-caret-left"></i></span></a>
<%= l @date.to_date, format: "%A %d de %B de %Y" %>
<a href="/lista/<%= @tomorrow %>"><span class="icon"><i class="fas fa-caret-right"></i></span></a>
</h1>
<% if @appointments.count > 0 %>
<table class="table is-bordered">
  <tr>
  	<th>Inicio</th>
  	<th>Fin</th>
    <th>Laboratorio</th>
  	<th>Estudiante</th>
  	<th>Asesor</th>
  	<th>Autorizó</th>
  	<th>Notas</th>
  </tr>
  <% @appointments.each do |a| %>
    <tr>
  	  <td><%= a.start / 100 %>:00</td>
  	  <td><%= a.end / 100 %>:00</td>
      <td><%= a.laboratory.name %></td>
  	  <td><%= a.student.first_name %> <%= a.student.last_name %> <%= a.student.last_name2 %></td>
  	  <td><%= a.student.staff.first_name rescue '-' %> <%= a.student.staff.last_name rescue '-' %></td>
  	  <td><%= a.user.first_name %> <%= a.user.last_name %></td>
  	  <td><%= a.notes %></td>
    </tr>
  <% end %>
</table>
<% else %>
No hay registros para este día.
<% end %>

app/views/appointments/new.html.erb
<%
students = Student.where(status: 1).order(:first_name, :last_name, :last_name2).pluck(:id, :first_name, :last_name, :last_name2)
student_options = {}
students.each do |p|
  student_options["#{p[1]} #{p[2]} #{p[3]}"] = p[0]
end

end_options = {}
next_appointment = @laboratory.appointments.where("appointment_date = ? AND start > ? AND status <> ?", @date, params[:hour].to_i * 100, Appointment::DELETED).order(:start).first
if next_appointment
  r = params[:hour].to_i  + 1
  next_r = next_appointment.start.to_i / 100
  while r <= next_r
    end_options["#{r}:00"] = r * 100
    r = r + 1;
  end
else
  r = params[:hour].to_i + 1
  while r <= 19
    end_options["#{r}:00"] = r * 100
    r = r + 1;
  end
end
%>
<nav class="level lab-level">
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle is-5">
        <strong><%= @laboratory.name %>: Nueva cita</strong>
      </p>
    </div>
  </div>
  <div class="level-right">
    
  </div>
</nav>
<%= form_for @appointment do |f| %>
<%= f.hidden_field :laboratory_id, :value => @laboratory.id %>
<%= f.hidden_field :start, :value => params[:hour].to_i * 100 %>
<%= f.hidden_field :appointment_date, :value => @date %>
<div class="columns is-mobile is-centered">
<div class="column is-narrow">
<table class="new-table">
<tr>
	<th>Estudiante</th>
	<td>
		<div class="select">
		<%= f.select :student_id, options_for_select(student_options), prompt: "-- Seleccionar estudiante --" %>
	    </div>
	</td>
</tr>
<tr>
	<th>Laboratorio:</th>
	<td><%= @laboratory.name %></td>
</tr>
<tr>
	<th>Día:</th>
	<td><%= l @date.to_date, format: "%A %d de %B de %Y" %></td>
</tr>
<tr>
	<th>Hora Inicio:</th>
	<td>
		<strong><%= params[:hour] %>:00</strong>
	</td>
</tr>
<tr>
	<th>Hora Fin:</th>
	<td>
		<span class="select"><%= f.select :end, options_for_select(end_options), prompt: "--" %></span>
	</td>
</tr>
<tr>
	<th style="vertical-align: top;">Notas:</th>
	<td>
		<%= f.text_area :notes, class: 'textarea' %>
	</td>
</tr>
</table>
<div class="save-button"><%= f.submit "Guardar", :class => 'button is-link' %></div>
</div>
</div>
<% end %>

app/views/appointments/no.html.erb
<div style="text-align: center; font-size: 120%; margin-top: 3em;">En semaforo rojo no se permite acceso a estudiantes</div>

app/views/appointments/show.html.erb
<% 
is_lab_admin = false
if authenticated?
  labadmin = LaboratoryAdmin.where(laboratory_id: @laboratory.id, user_id: current_user.id)
  is_lab_admin = true if labadmin.count > 0
end
sessions = {}
@laboratory.appointments.where('appointment_date = ? AND status <> ?', @date, Appointment::DELETED ).order(:start).each do |s|
  
  (8..18).each do |r| 
  	h = r * 100
    if h.to_i == s.start.to_i
      sessions[h] = s
    end
  end
end
%>
<nav class="level lab-level">
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle is-5">
        <strong><%= @laboratory.name %></strong>
      </p>
    </div>
  </div>
  <div class="level-right" style="text-align: center;">
    <a href="/laboratorios/<%= @laboratory.id %>/<%= @yesterday %>"><span class="icon"><i class="fas fa-caret-left"></i></span></a>
    <span class="date"><%= l @date.to_date, format: "%A %d de %B de %Y" %></span>
    <a href="/laboratorios/<%= @laboratory.id %>/<%= @tomorrow %>"><span class="icon"><i class="fas fa-caret-right"></i></span></a>
  </div>
</nav>
<table class="sessions-table">
  <tr>
  	<th style="text-align: center;">Hora</th>
  	<th>Sesión</th>
  </tr>
  <% rowspan = 0 %>
  <% c = 0 %>
  <% (8..18).each do |r| %>
    <% h = r * 100 %>
    <tr>
    	<td class="td-hora"><%= "#{r}:00" %></td>
    	<% if sessions[h.to_i] %>
    	  <% c = c + 1 %>
    	  <% rowspan = (sessions[h.to_i].end - sessions[h.to_i].start) / 100 %>
    	  <td class="appointment c<%= c %>" rowspan="<%= rowspan %>">
    	  	   <div class="appointment-actions">
    	  	   <% if sessions[h.to_i].status == Appointment::PROGRAMMED %>
    	  	     <span class="tag">Programado</span>
    	  	   <% end %>
    	  	   <% if sessions[h.to_i].status == Appointment::ASSIST %>
    	  	     <span class="tag is-success">Asistió</span>
    	  	   <% end %>
    	  	   <% if sessions[h.to_i].status == Appointment::NOT_ASSIST %>
    	  	     <span class="tag is-danger">No asistió</span>
    	  	   <% end %>
    	  	   <% if authenticated? && is_lab_admin %>
    	  	      <a data-id="<%= sessions[h.to_i].id %>" class="assist" title="Asistió" href=""><span class="icon"><i class="fas fa-check"></i></span></a> 
    	  	      <a data-id="<%= sessions[h.to_i].id %>" class="no-assist" title="No asistió" href=""><span class="icon"><i class="fas fa-times"></i></span></a> 
    	  	      <a data-id="<%= sessions[h.to_i].id %>" class="remove" title="Eliminar" href=""><span class="icon"><i class="fas fa-trash"></i></span></a>
    	  	   <% end %>
    		   </div>
    		   <span class="student-name"><%= sessions[h.to_i].student.first_name %> <%= sessions[h.to_i].student.last_name %></span><br>
    		   <span class="supervisor-name">Asesor: <%= sessions[h.to_i].student.staff.first_name rescue '-' %> <%= sessions[h.to_i].student.staff.last_name rescue '-' %></span><br>
    		   <span class="user-name">Autoriza: <%= sessions[h.to_i].user.first_name %> <%= sessions[h.to_i].user.last_name %></span><br>
    		   <span class="hours">De: <%= sessions[h.to_i].start / 100 %>:00 a <%= sessions[h.to_i].end / 100 %>:00</span><br>
    		   <% if sessions[h.to_i].notes %>
    		     <p>Notas: <%= sessions[h.to_i].notes %></p>
    		   <% end %>
    	   </td>
    	<% else %>
    	  <% rowspan = rowspan - 1 if rowspan > 0 %>
    	  <% if rowspan == 0 %>
    	    <td>
    	      <% if authenticated? && is_lab_admin %>  
    	    	<a class="button" href="<%= new_appointment_path %>?laboratory_id=<%= @laboratory.id %>&date=<%= @date %>&hour=<%= r %>">Agregar</a>
    	      <% end %>
    	    </td>
    	  <% end %>
        <% end %>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='has-navbar-fixed-top'>
  <head>
    <title>Agenda de Laboratorios</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-success" role="navigation" aria-label="main navigation">
      <div class="navbar-brand" style="float: left;"><a class="navbar-item" href="/"><strong>Agenda de Laboratorio</strong></a></div>
      <div class="navbar-item" style="float: left; margin-top: 0.3em;">
        <% if authenticated? %>
            <span style="color: #fff; margin-right: 2em;"><%= current_user.first_name %> <%= current_user.last_name %></span>
            <a href="/logout">[ Salir ]</a>
        <% else %>
          <a href="/auth/google_oauth2">[ Entrar ]</a>
        <% end %>
      </div>
      <div class="is-clearfix"></div>
    </nav>
    <div class="controls">
      <% 

      if authenticated? 
        labs = []
        current_user.laboratory_admins.each do |la|
          labs << la.laboratory_id
        end
        laboratories = Laboratory.order(:name).where(id: labs).pluck(:id, :name)
      else  
        laboratories = Laboratory.order(:name).pluck(:id, :name)
      end
      laboratory_options = {}
      laboratories.each do |p|
        laboratory_options[p[1]] = p[0]
      end
      if @laboratory 
        lab_id = @laboratory.id
      else
        lab_id = ''
      end
      %>
      <div class="columns">
      <div class="field column">
        <div class="select is-fullwidth">
          <%= select_tag :laboratory, options_for_select(laboratory_options, lab_id), {:prompt => "-- Selecciona laboratorio --"} %>
        </div>
      </div>
      <div class="field column">
        <input class="input" type="date" name="date" id="date" value="<%= @date %>">
      </div>
      </div>
    </div>
    </div>
    <%= yield %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </body>
</html>

app/views/layouts/standalone.html.erb
<!DOCTYPE html>
<html class='has-navbar-fixed-top'>
  <head>
    <title>Agenda de Laboratorios</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </body>
</html>